[build-system]
requires = ['setuptools', 'wheel']
build-backend = "setuptools.build_meta"

[project]
name='umlextensions'
dynamic = ["version"]
description = 'Plugins for umldiagrammer'
readme = "README.md"
authors = [{name = 'Humberto A. Sanchez II', email = 'Humberto.A.Sanchez.II@gmail.com'}]
maintainers = [{name = 'Humberto A. Sanchez II', email = 'Humberto.A.Sanchez.II@gmail.com'}]
keywords = ['umldiagrammer,graphical,uml shapes,python']
license     = 'AGPL-1.0-or-later'

classifiers = [
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Operating System :: MacOS :: MacOS X",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    'wxPython~=4.2.3',
    'codeallybasic>=1.30.0',
    'codeallyadvanced>=2.2.0',
    'pyutmodelv2>=2.2.6',
    'umlshapes>=0.9.310',
    'antlr4-python3-runtime==4.13.2',

]

[project.optional-dependencies]

test = [
  'mypy==1.17.1',
  'mypy-extensions==1.1.0',
  'types-Deprecated==1.2.15.20250304',
  'html-testRunner~=1.2.1',
]

deploy = [
    "wheel==0.45.1",
    "setuptools==80.9.0",
    "twine==6.1.0",
    "build==1.3.0",
    'pkginfo==1.12.1.2'
]

[project.urls]
Repository = 'https://github.com/hasii2011/umlextensions'


[tool.setuptools.packages.find]
where = ['src']

[tool.setuptools.package-data]
'umlextensions.resources' = ['loggingConfiguration.json']

[tool.setuptools.dynamic]
version = {attr = 'umlextensions.__version__'}

[project.scripts]

pyfabricate = "umlextensions.MainClass:commandHandler"
