
from unittest import TestSuite
from unittest import main as unitTestMain

from antlr4 import FileStream
from antlr4 import CommonTokenStream
from antlr4.error.ErrorListener import ConsoleErrorListener

from codeallybasic.UnitTestBase import UnitTestBase

from umlmodel.Class import Class
from umlmodel.Field import Field
from umlmodel.Field import Fields
from umlmodel.FieldType import FieldType
from umlmodel.enumerations.Stereotype import Stereotype

from umlextensions.input.python.pythonpegparser.PythonLexer import PythonLexer
from umlextensions.input.python.pythonpegparser.PythonParser import PythonParser
from umlextensions.input.python.visitor.ParserTypes import ModelClassName

from umlextensions.input.python.visitor.ParserTypes import ModelClasses
from umlextensions.input.python.visitor.PythonPegParserClassVisitor import PythonPegParserClassVisitor

from tests.umlextensions.input.python.visitor.BaseTestPythonPegVisitor import BaseTestPythonPegVisitor
from tests.umlextensions.input.python.visitor.BaseTestPythonPegVisitor import ModelFieldHashIndex

class PythonErrorListener(ConsoleErrorListener):
    pass


class TestPythonPegParserClassVisitor(BaseTestPythonPegVisitor):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 27 October 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testParseEnumeration(self):

        modelClasses: ModelClasses = self._parseSimpleEnumeration()
        classNames = modelClasses.keys()
        self.assertIn('SimpleEnumeration', classNames, 'Missing enumeration')

    def testParseEnumerationFields(self):
        modelClasses: ModelClasses = self._parseSimpleEnumeration()
        modelClass:   Class        = modelClasses[ModelClassName('SimpleEnumeration')]

        self.assertEqual(Stereotype.ENUMERATION, modelClass.stereotype, 'Enumerations need to be stereotyped correctly')

        self.assertEqual(5, len(modelClass.fields), 'Number of enumeration fields does not match')

    def testEnumerationFieldValues(self):

        modelClasses: ModelClasses = self._parseSimpleEnumeration()
        modelClass:   Class        = modelClasses[ModelClassName('SimpleEnumeration')]

        fields: Fields         = modelClass.fields
        index:  ModelFieldHashIndex = self._makeFieldIndex(modelFields=fields)

        enumField: Field = index['Fks']
        self.assertEqual("'Frances K. Sanchez'", enumField.defaultValue, 'Did not parse value correctly')
        self.assertEqual(FieldType(''),           enumField.type,        'Should have an empty field type')

    def testClassParsed(self):

        tree:    PythonParser.File_inputContext = self._setupPegBasedParser('SimpleClass.py')
        visitor: PythonPegParserClassVisitor    = PythonPegParserClassVisitor()

        visitor.visit(tree)

        modelClasses: ModelClasses = visitor.modelClasses
        classNames = modelClasses.keys()
        self.assertIn('SimpleClass', classNames, 'Missing class name')
        modelClass: Class = modelClasses[ModelClassName('SimpleClass')]
        self.logger.debug(f'{modelClass=}')

    def testRetrieveClassNames(self):

        tree:    PythonParser.File_inputContext = self._setupPegBasedParser('AssociationClasses.py')
        visitor: PythonPegParserClassVisitor    = PythonPegParserClassVisitor()

        visitor.visit(tree)
        #
        # 3 regular and 2 synthetic classes
        #
        self.assertEqual(5, len(visitor.modelClasses), 'Oops class names parsed, mismatch')

    def testSynthesizedTypes(self):

        tree:    PythonParser.File_inputContext = self._setupPegBasedParser('AssociationClasses.py')
        visitor: PythonPegParserClassVisitor    = PythonPegParserClassVisitor()

        visitor.visit(tree)

        modelClasses: ModelClasses = visitor.modelClasses

        classNames = modelClasses.keys()
        self.assertIn('Pages',    classNames, 'Missing `Pages` class name')
        self.assertIn('Chapters', classNames, 'Missing `Chapters` class name')

    def testNonClassAssignmentIgnore(self):

        tree:    PythonParser.File_inputContext = self._setupPegBasedParser('NoContainingClassFile.py')
        visitor: PythonPegParserClassVisitor    = PythonPegParserClassVisitor()

        visitor.visit(tree)
        modelClasses: ModelClasses = visitor.modelClasses

        syntheticNames = modelClasses.keys()
        self.assertIn('SyntheticType', syntheticNames, 'Missing class name')

    def _parseSimpleEnumeration(self) -> ModelClasses:
        tree:    PythonParser.File_inputContext = self._setupPegBasedParser('SimpleEnumeration.py')
        visitor: PythonPegParserClassVisitor      = PythonPegParserClassVisitor()

        visitor.visit(tree)
        return visitor.modelClasses

    def _setupPegBasedParser(self, fileName: str) -> PythonParser.File_inputContext:

        fqFileName: str = UnitTestBase.getFullyQualifiedResourceFileName(BaseTestPythonPegVisitor.RESOURCES_TEST_CLASSES_PACKAGE_NAME, fileName)

        fileStream: FileStream  = FileStream(fqFileName)
        lexer:      PythonLexer = PythonLexer(fileStream)

        stream: CommonTokenStream = CommonTokenStream(lexer)
        parser: PythonParser      = PythonParser(stream)

        parser.removeParseListeners()
        parser.addErrorListener(PythonErrorListener())

        tree: PythonParser.File_inputContext = parser.file_input()
        if parser.getNumberOfSyntaxErrors() != 0:
            self.logger.error(f'File contains {parser.getNumberOfSyntaxErrors()} syntax errors')
            self.assertTrue(False, f'File contains {parser.getNumberOfSyntaxErrors()} syntax errors')

        return tree

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestPythonPegParserClassVisitor))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
