
from typing import List
from unittest import TestSuite
from unittest import main as unitTestMain

from importlib.resources import files
from importlib.resources.abc import Traversable

from codeallyadvanced.ui.UnitTestBaseW import UnitTestBaseW
from umlmodel.Class import Class

from umlshapes.frames.ClassDiagramFrame import ClassDiagramFrame
from umlshapes.lib.ogl import OGLInitialize
from umlshapes.pubsubengine.UmlPubSubEngine import UmlPubSubEngine

from tests.umlextensions.input.python.visitor.BaseTestPythonPegVisitor import BaseTestPythonPegVisitor
from umlextensions.input.python.PythonToUmlShapes import PythonToUmlShapes
from umlextensions.input.python.PythonToUmlShapes import UmlClassesDict
from umlextensions.input.python.visitor.ParserTypes import ModelClassName
from umlextensions.input.python.visitor.ParserTypes import ModelClasses

EXPECTED_PASS1_CLASSES: int = 2


class TestPythonToUmlShapes(UnitTestBaseW):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 28 October 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()
        OGLInitialize()
        self._umlPubSubEngine:   UmlPubSubEngine   = UmlPubSubEngine()
        self._classDiagramFrame: ClassDiagramFrame = ClassDiagramFrame(parent=self._topLevelWindow, umlPubSubEngine=self._umlPubSubEngine)

    def tearDown(self):
        super().tearDown()

    def testPass1(self):
        traversable: Traversable = files(BaseTestPythonPegVisitor.RESOURCES_TEST_CLASSES_PACKAGE_NAME)
        fileList:    List[str]   = ['SimpleClass.py', 'SimpleDataClass.py']

        pythonToUmlShapes: PythonToUmlShapes = PythonToUmlShapes(classDiagramFrame=self._classDiagramFrame, umlPubSubEngine=self._umlPubSubEngine)
        modelClasses:      ModelClasses       = pythonToUmlShapes.pass1(directoryName=str(traversable),
                                                                        files=fileList,
                                                                        progressCallback=self._progressCallback,
                                                                        )

        self.assertEqual(EXPECTED_PASS1_CLASSES, len(modelClasses), 'Not enough data model classes')

        simpleClass: Class = modelClasses[ModelClassName('SimpleClass')]
        self.assertEqual('SimpleClass', simpleClass.name, 'Name mismatch')

        simpleClass = modelClasses[ModelClassName('SimpleDataClass')]
        self.assertEqual('SimpleDataClass', simpleClass.name, 'Name mismatch')

    def testPass2DeepInheritance(self):

        traversable: Traversable = files(BaseTestPythonPegVisitor.RESOURCES_TEST_CLASSES_PACKAGE_NAME)
        fileList:    List[str]   = ['DeepInheritance.py']

        pythonToUmlShapes: PythonToUmlShapes = PythonToUmlShapes(classDiagramFrame=self._classDiagramFrame, umlPubSubEngine=self._umlPubSubEngine)
        modelClasses:      ModelClasses       = pythonToUmlShapes.pass1(directoryName=str(traversable),
                                                                        files=fileList,
                                                                        progressCallback=self._progressCallback,
                                                                        )
        self.logger.info(f'{len(modelClasses)=}')

        updatedModelClasses: ModelClasses = pythonToUmlShapes.pass2(directoryName=str(traversable),
                                                                    files=fileList,
                                                                    modelClasses=modelClasses,
                                                                    progressCallback=self._progressCallback
                                                                    )
        self.logger.info(f'{len(updatedModelClasses)=}')

        umlClassesDict: UmlClassesDict = pythonToUmlShapes.generateUmlClasses(updatedModelClasses)

        self.logger.info(f'{umlClassesDict=}')

        pythonToUmlShapes.generateLinks(umlClassesDict=umlClassesDict)
        self.assertEqual(4, len(pythonToUmlShapes.umlLinks), 'Did not generate enough inheritance links')

    def testPass2Associations(self):

        traversable: Traversable = files(BaseTestPythonPegVisitor.RESOURCES_TEST_CLASSES_PACKAGE_NAME)
        fileList:    List[str]   = ['AssociationClasses.py']

        pythonToUmlShapes: PythonToUmlShapes = PythonToUmlShapes(classDiagramFrame=self._classDiagramFrame, umlPubSubEngine=self._umlPubSubEngine)
        modelClasses:      ModelClasses       = pythonToUmlShapes.pass1(directoryName=str(traversable),
                                                                        files=fileList,
                                                                        progressCallback=self._progressCallback,
                                                                        )
        self.logger.info(f'{len(modelClasses)=}')

        updatedModelClasses: ModelClasses = pythonToUmlShapes.pass2(directoryName=str(traversable),
                                                                    files=fileList,
                                                                    modelClasses=modelClasses,
                                                                    progressCallback=self._progressCallback
                                                                    )
        self.logger.info(f'{len(updatedModelClasses)=}')

        umlClassesDict: UmlClassesDict = pythonToUmlShapes.generateUmlClasses(updatedModelClasses)

        self.logger.info(f'{umlClassesDict=}')
        pythonToUmlShapes.generateLinks(umlClassesDict=umlClassesDict)

        self.assertEqual(2, len(pythonToUmlShapes.umlLinks), 'Did not generate enough association links')

    def _progressCallback(self, currentFileCount: int, message: str):
        self.logger.info(f'{currentFileCount=} {message=}')

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestPythonToUmlShapes))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
