graph [
	directed 1
	version  1.0
	label "GML for DefaultGraphName"
	comment "Generated by GML Exporter Version 2.0.0"
	node [
		id "10000"
		label "ClassName_10000"
		graphics [
			x 100
			y 100
			z 0
			w 50
			h 50
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id "10010"
		label "ClassName_10010"
		graphics [
			x 175
			y 200
			z 0
			w 50
			h 50
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	edge [
		id "1024"
		source "10000"
		target "10010"
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 22
					y 44
					z 0
				]
				point [
					x 100
					y 100
					z 0
				]
				point [
					x 1024
					y 450
					z 0
				]
			]
		]
	]
]
